name: copy_with
description: Copy with generator
version: 0.0.2
author: The Next App <info@thenextapp.nl>
homepage: https://github.com/thenextappnl/copy_with

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  build:
  source_gen:
  analyzer: '>=0.36.0 <0.39.0'
  copy_with_annotation:

dev_dependencies:
  build_test:
  build_runner:
  test: