name: copy_with
description: Provides builder and generator for the copy_with_annotation package
version: 0.0.2+2
author: The Next App <info@thenextapp.nl>
homepage: https://github.com/thenextappnl/copy_with

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  build: '>=1.1.0 <1.3.0'
  source_gen: '>=0.8.3 <0.9.5'
  analyzer: '>=0.36.0 <0.40.0'
  copy_with_annotation: '^0.0.2'

dev_dependencies:
  build_test: '>=0.10.0 <0.11.0'
  build_runner: '>=1.5.0 <1.8.0'
  test: '>=1.6.0 <1.9.5'