name: copy_with_annotation
description: This package generates a copyWith method using build_runner and json_serializable packages
version: 0.1.0
author: The Next App <info@thenextapp.nl>
homepage: https://github.com/thenextappnl/copy_with

environment:
  sdk: '>=2.6.0 <3.0.0'